Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2022-12, with the labels that each got.

#885 Filters for issue #584
  activity_browser/bwutils/multilca.py
  activity_browser/controllers/project.py
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/settings.py
  activity_browser/ui/menu_bar.py
  activity_browser/ui/wizards/settings_wizard.py
  tests/test_settings.py
  tests/test_settings_wizard.py
Labels: type:feature, info:UI, prio:normal

#890 Update meta.yaml
  ci/recipe/stable/meta.yaml
Labels: ci

#895 Minor changes to avoid issues related to np.bool deprecation
  activity_browser/ui/figures.py
  activity_browser/ui/tables/models/base.py
Labels: change

#896 Fix for issue #635 and corrections to previous commit for issue 590
  activity_browser/bwutils/multilca.py
  activity_browser/ui/tables/models/lca_results.py
Labels: bug, change

#897 helps to address issue 692
  activity_browser/bwutils/exporters.py
Labels: bug

#898 issue 709
  activity_browser/ui/tables/models/lca_setup.py
  activity_browser/ui/tables/models/scenarios.py
Labels: change

#902 Small bugs
  activity_browser/ui/tables/models/lca_results.py
  activity_browser/ui/tables/models/lca_setup.py
Labels: bug

#903 Classifications in the ActivitiesBiosphereTable
  activity_browser/bwutils/metadata.py
  activity_browser/ui/tables/models/inventory.py
Labels: type:feature

#900 issue 597
  activity_browser/bwutils/strategies.py
  activity_browser/controllers/database.py
  activity_browser/ui/widgets/__init__.py
  activity_browser/ui/widgets/dialog.py
Labels: info:usability, change

#904 Minor changes in ActivityTab __init__ routine
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/layouts/tabs/activity.py
Labels: bug

#894 Implement table filters
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/static/icons/main/filter.png
  activity_browser/static/icons/main/filter_outline.png
  activity_browser/ui/icons.py
  activity_browser/ui/tables/impact_categories.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/tables/lca_results.py
  activity_browser/ui/tables/models/base.py
  activity_browser/ui/tables/models/impact_categories.py
  activity_browser/ui/tables/models/inventory.py
  activity_browser/ui/tables/models/lca_results.py
  activity_browser/ui/tables/views.py
  activity_browser/ui/widgets/dialog.py
Labels: type:feature
