Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2022-04, with the labels that each got.

#751 Revise the tree model for the impact categories.
  activity_browser/ui/tables/models/impact_categories.py
Labels: prio:low, documentation

#761 Activity details tables keep show/hide state when activity is updated
  activity_browser/ui/widgets/activity.py
Labels: prio:low, bug

#729 Allow deleting of processes/activities with downstream consumers
  activity_browser/controllers/activity.py
Labels: bug

#743 Scenario loading bugfix + Better error message on missing keys
  activity_browser/bwutils/superstructure/excel.py
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/ui/widgets/__init__.py
  activity_browser/ui/widgets/dialog.py
Labels: bug

#765 Fix negative contributions grouping under Rest issue
  activity_browser/bwutils/multilca.py
Labels: bug

#779 Enable Parameter comments + show/hide activity parameters table
  activity_browser/layouts/tabs/parameters.py
  activity_browser/ui/tables/models/parameters.py
  activity_browser/ui/tables/parameters.py
  tests/test_uncertainty.py
Labels: change
