Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2022-09, with the labels that each got.

#833 fix #832
  activity_browser/static/javascript/navigator.js
Labels: bug

#834 fix #794
  activity_browser/ui/web/base.py
Labels: bug

#835 fix svg arrowhead urls (path end-markers)
  activity_browser/static/javascript/navigator.js
Labels: bug

#837 add database name to sankey reference flow dropdown
  activity_browser/ui/web/sankey_navigator.py
Labels: type:feature

#843 Fix #842
  activity_browser/ui/tables/models/impact_categories.py
Labels: type:bug

#846 ensure method tree is updated when project is changed
  activity_browser/ui/tables/models/impact_categories.py
Labels: type:bug

#848 Fix #788 for activities table
  activity_browser/ui/tables/models/inventory.py
Labels: type:bug
