Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2022-11, with the labels that each got.

#733 Automated release with changelog for the stable version
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  ci/changelog-configuration.json
  ci/conda-envs/ab.yml
Labels: info:ci

#875 Build and upload activity-browser-arm with github actions
  .github/workflows/main.yaml
  ci/conda-envs/ab_arm.yml
  ci/recipe/arm/meta.yaml
Labels: ci

#877 Added information to the README.md file concerning installing Ecoinvent database installation
  README.md
  activity_browser/controllers/parameter.py
  activity_browser/layouts/main.py
  activity_browser/ui/menu_bar.py
Labels: info:UI, info:documentation, bug

#879 This is a pull request related to issues 270 and 759
  activity_browser/bwutils/superstructure/__init__.py
  activity_browser/bwutils/superstructure/excel.py
  activity_browser/bwutils/superstructure/utils.py
  activity_browser/controllers/activity.py
  activity_browser/controllers/database.py
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/layouts/tabs/LCA_setup.py
  activity_browser/layouts/tabs/activity.py
  activity_browser/signals.py
  activity_browser/ui/tables/LCA_setup.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/tables/models/activity.py
  activity_browser/ui/tables/models/history.py
  activity_browser/ui/tables/parameters.py
  tests/test_add_default_data.py
Labels: info:UI
