Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2023-10, with the labels that each got.

#1051 Add 'duplicate to new location' option for duplicating processes
  activity_browser/controllers/activity.py
  activity_browser/layouts/tabs/activity.py
  activity_browser/signals.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/tables/models/inventory.py
  activity_browser/ui/widgets/__init__.py
  activity_browser/ui/widgets/activity.py
  activity_browser/ui/widgets/dialog.py
Labels: change

#1045 Minor Contribution analysis bugfix
  activity_browser/bwutils/multilca.py
  activity_browser/layouts/tabs/LCA_results_tab.py
  activity_browser/ui/tables/models/lca_results.py
  activity_browser/ui/web/sankey_navigator.py
Labels: bug, change

#1041 Update Brightway2 requirement
  README.md
  ci/recipe/stable/meta.yaml
Labels: documentation, change

#1069 Updates to the functions get_relevant_flows and get_relevant_activities
  activity_browser/bwutils/superstructure/activities.py
  activity_browser/bwutils/superstructure/excel.py
Labels: bug

#1083 Multiple sdf update
  activity_browser/bwutils/superstructure/manager.py
  tests/test_uncertainty_wizard.py
Labels: bug

#1095 Use node16 actions everywhere
  .github/workflows/install-canary.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yaml
Labels: ci

#1096 Remove the special build for arm architecture
  .github/workflows/main.yaml
  ci/conda-envs/ab_arm.yml
  ci/recipe/arm/meta.yaml
Labels: ci

#1093 Install canary updates
  .github/workflows/install-canary.yaml
Labels: ci
