Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2023-09, with the labels that each got.

#1028 Additional scenario checks
  activity_browser/bwutils/errors.py
  activity_browser/bwutils/superstructure/__init__.py
  activity_browser/bwutils/superstructure/dataframe.py
  activity_browser/bwutils/superstructure/excel.py
  activity_browser/bwutils/superstructure/file_dialogs.py
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/bwutils/superstructure/utils.py
  activity_browser/layouts/tabs/LCA_setup.py
Labels: type:bug, info:UI

#1034 Add descriptions to each signal
  activity_browser/controllers/plugin.py
  activity_browser/settings.py
  activity_browser/signals.py
Labels: type:documentation

#1035 Fix CF values not updated
  activity_browser/controllers/plugin.py
  activity_browser/settings.py
  activity_browser/signals.py
  activity_browser/ui/tables/impact_categories.py
  activity_browser/ui/tables/models/impact_categories.py
Labels: type:bug

#1029 Fix CF values not updated
  activity_browser/signals.py
  activity_browser/ui/tables/impact_categories.py
  activity_browser/ui/tables/models/impact_categories.py
Labels: type:bug

#1040 Update logging file timestamp format
  activity_browser/logger.py
Labels: change

#1038 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/something_else.yml
Labels: documentation

#1050 Excel import bug
  activity_browser/bwutils/superstructure/excel.py
Labels: bug
