Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2023-05, with the labels that each got.

#966 Ensure correct package version for conda-forge AB
  setup.py
Labels: ci

#969 Image links
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/layouts/tabs/LCA_setup.py
  resources/sdf_addition_combination.png
  resources/sdf_product_combination.png
Labels: type:bug, type:documentation

#968 Marc patch
  activity_browser/layouts/tabs/activity.py
Labels: type:bug

#970 Scenario fix
  activity_browser/bwutils/commontasks.py
  activity_browser/bwutils/errors.py
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/bwutils/superstructure/mlca.py
  activity_browser/layouts/tabs/LCA_results_tab.py
  activity_browser/layouts/tabs/LCA_setup.py
  resources/sdf_addition_combination.png
  resources/sdf_product_combination.png
Labels: type:bug, type:documentation

#976 Project name tooltips
  activity_browser/ui/tables/projects.py
Labels: info:UI
