Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2023-11, with the labels that each got.

#1085 Adding error message if no scenario file is loaded in a scenario LCA
  activity_browser/bwutils/superstructure/mlca.py
Labels: change

#1106 Resolve excel database exporter bug
  activity_browser/bwutils/exporters.py
Labels: bug

#1111 Update copyright and license information and link it to one place
  activity_browser/static/startscreen/welcome.html
  activity_browser/ui/menu_bar.py
Labels: change

#1110 Minor improvements to duplicating to new location
  activity_browser/controllers/activity.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/widgets/dialog.py
Labels: bug, change

#1114 AB now stores the version in the log file
  activity_browser/application.py
Labels: documentation

#1118 Remove and/or update conda envs
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  ci/conda-envs/ab.yml
  ci/conda-envs/ab_dev.yml
  ci/conda-envs/build.yml
  ci/conda-envs/test.yml
Labels: ci

#1119 Reorganize workflow files
  .github/changelog-configuration.json
  .github/conda-envs/build.yml
  .github/conda-envs/test.yml
  .github/dev-recipe/meta.yaml
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  recipe/meta.yaml
Labels: ci

#1120 Use micromamba instead of miniconda to speed up tests
  .github/workflows/main.yaml
Labels: ci

#1121 Update install instructions to use libmamba solver with conda
  README.md
Labels: documentation

#1130 Add tooltip to table cells with content overflow
  activity_browser/ui/tables/models/base.py
Labels: change

#1136 Add - copy on impact category copy
  activity_browser/controllers/project.py
  activity_browser/ui/tables/impact_categories.py
  activity_browser/ui/widgets/dialog.py
Labels: change

#1138 Resolve bug with switching project on delete
  activity_browser/controllers/project.py
Labels: bug, change
