Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2023-02, with the labels that each got.

#927 Database search filter integration
  activity_browser/layouts/tabs/project_manager.py
  activity_browser/ui/tables/inventory.py
Labels: bug

#928 Changes to the ability to import scenarios using different formats (WIP)
  activity_browser/bwutils/superstructure/file_imports.py
  activity_browser/layouts/tabs/LCA_setup.py
  activity_browser/ui/widgets/dialog.py
Labels: type:feature, change

#930 Minor update to settings_wizard
  activity_browser/ui/wizards/settings_wizard.py
Labels: bug

#933 Issue 932b
  activity_browser/bwutils/superstructure/manager.py
Labels: bug

#936 Welcome links
  activity_browser/static/startscreen/welcome.html
Labels: type:documentation

#938 Sdf field interpretation
  activity_browser/bwutils/superstructure/file_imports.py
Labels: type:bug

#941 Issue 926
  activity_browser/ui/tables/views.py
Labels: type:bug
