Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2023-08, with the labels that each got.

#1007 Table updates (double click)
  activity_browser/ui/tables/activity.py
  activity_browser/ui/tables/models/activity.py
  activity_browser/ui/tables/models/parameters.py
  activity_browser/ui/tables/parameters.py
Labels: info:UI

#1008 Title tooltips
  activity_browser/layouts/tabs/impact_categories.py
Labels: info:UI

#1009 Adds further checks on the creation of the traingular and bernoulli distributions
  activity_browser/ui/wizards/uncertainty.py
Labels: type:bug

#1014 Corrections to allow the dynamic importing of the ecoinvent biosphere flows
  activity_browser/ui/widgets/biosphere_update.py
Labels: info:brightway

#1015 Relinking
  activity_browser/controllers/activity.py
  activity_browser/controllers/database.py
Labels: type:bug

#1017 Heatmap correction
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/ui/figures.py
Labels: type:bug

#1020 Databases as tabs
  activity_browser/bwutils/commontasks.py
  activity_browser/controllers/database.py
  activity_browser/layouts/panels/panel.py
  activity_browser/layouts/tabs/project_manager.py
  activity_browser/signals.py
  activity_browser/ui/statusbar.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/tables/models/inventory.py
  tests/test_add_default_data.py
Labels: type:feature

#1023 Updated scenario calculations
  activity_browser/bwutils/superstructure/mlca.py
Labels: type:bug

#1025 Updated scenarios
  activity_browser/__init__.py
  activity_browser/bwutils/calculations.py
  activity_browser/bwutils/errors.py
  activity_browser/bwutils/multilca.py
  activity_browser/bwutils/superstructure/__init__.py
  activity_browser/bwutils/superstructure/activities.py
  activity_browser/bwutils/superstructure/dataframe.py
  activity_browser/bwutils/superstructure/excel.py
  activity_browser/bwutils/superstructure/file_dialogs.py
  activity_browser/bwutils/superstructure/file_imports.py
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/bwutils/superstructure/mlca.py
  activity_browser/controllers/database.py
  activity_browser/layouts/panels/panel.py
  activity_browser/layouts/tabs/LCA_results_tab.py
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/layouts/tabs/LCA_setup.py
  activity_browser/layouts/tabs/parameters.py
  activity_browser/static/icons/context/critical.png
  activity_browser/static/icons/context/warning.png
  activity_browser/ui/icons.py
  activity_browser/ui/tables/models/inventory.py
  activity_browser/ui/widgets/__init__.py
  activity_browser/ui/widgets/dialog.py
  activity_browser/ui/wizards/db_import_wizard.py
Labels: type:bug, type:feature, info:UI
