Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2024-09, with the labels that each got.

#1350 Move wiki to repo + Automated updating of wiki
  .github/scripts/update_wiki.sh
  .github/workflows/manual_update_wiki.yml
  .github/workflows/release.yaml
  CONTRIBUTING.md
  activity_browser/docs/wiki/Global-Sensitivity-Analysis.md
  activity_browser/docs/wiki/Home.md
  activity_browser/docs/wiki/Monte-Carlo-Simulation.md
  setup.py
Labels: documentation

#1357 Fixed broken database delete signalling
  activity_browser/mod/bw2data/backends/base.py
Labels: bug, prio:high

#1341 Make the dependent biosphere database visible in the CF table
  activity_browser/ui/tables/impact_categories.py
  activity_browser/ui/tables/models/impact_categories.py
Labels: change

#1347 Better plugin logging
  activity_browser/controllers/plugin.py
  activity_browser/settings.py
Labels: change

#1360 Migrations fix
  activity_browser/actions/__init__.py
  activity_browser/actions/migrations_install.py
  activity_browser/mod/bw2io/ecoinvent.py
  activity_browser/ui/menu_bar.py
  tests/actions/test_various_actions.py
Labels: bug, change

#1352 Readme + Wiki update
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  activity_browser/docs/wiki/Activities.md
  activity_browser/docs/wiki/Databases.md
  activity_browser/docs/wiki/Flow-Scenarios.md
  activity_browser/docs/wiki/Getting-Started.md
  activity_browser/docs/wiki/Graph-Explorer.md
  activity_browser/docs/wiki/Home.md
  activity_browser/docs/wiki/Impact-Categories.md
  activity_browser/docs/wiki/Installation-Guide.md
  activity_browser/docs/wiki/LCA-Calculation-Setups.md
  activity_browser/docs/wiki/LCA-Results.md
  activity_browser/docs/wiki/Monte-Carlo-Simulation.md
  activity_browser/docs/wiki/Need-Help.md
  activity_browser/docs/wiki/Parameters.md
  activity_browser/docs/wiki/Plugins.md
  activity_browser/docs/wiki/Projects.md
  activity_browser/docs/wiki/Settings.md
  activity_browser/docs/wiki/Tutorials.md
  activity_browser/docs/wiki/Uncertainty.md
  activity_browser/docs/wiki/_Footer.md
  activity_browser/docs/wiki/_Sidebar.md
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_act_details_1.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_act_details_2.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_act_details_3.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_create_act_context.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_create_db.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_db_graph_explorer.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_graph_explorer.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_lca_results.png
  activity_browser/docs/wiki/assets/_tutorials/first_lca_tutorial_lca_setup.png
  activity_browser/docs/wiki/assets/activitybrowser.png
  activity_browser/docs/wiki/assets/brightway_org-scheme.png
  activity_browser/docs/wiki/assets/global_sensitivity_analysis_results.jpg
  activity_browser/docs/wiki/assets/monte_carlo_results.jpg
  activity_browser/docs/wiki/assets/overview_global_sensitivity_analysis_setup.jpg
  activity_browser/docs/wiki/assets/overview_monte_carlo_setup.jpg
  activity_browser/docs/wiki/assets/project_setup_dialog_bio_vsn.png
  activity_browser/docs/wiki/assets/project_setup_dialog_choose_type.png
  activity_browser/docs/wiki/assets/project_setup_dialog_ei_login.png
  activity_browser/docs/wiki/assets/project_setup_dialog_ei_vsn_and_model.png
  activity_browser/docs/wiki/assets/project_tab_until_databases.png
  activity_browser/ui/menu_bar.py
Labels: documentation

#1363 Fix Impact Category list view actions
  activity_browser/ui/tables/impact_categories.py
Labels: bug

#1362 Project selection through project menu
  activity_browser/layouts/main.py
  activity_browser/ui/menu_bar.py
Labels: change

#1364 Added export to .csv button to LCA results tabs
  activity_browser/layouts/tabs/LCA_results_tabs.py
Labels: change

#1365 Fixes bug where CF amount can't be edited
  activity_browser/ui/tables/impact_categories.py
Labels: bug

#1369 Wiki updates
  activity_browser/docs/wiki/Databases.md
  activity_browser/docs/wiki/Projects.md
Labels: documentation

#1380 Switching projects only if the new project is not already the current project
  activity_browser/actions/project/project_switch.py
Labels: bug

#1367 Menu bar refactor
  activity_browser/ui/menu_bar.py
Labels: change

#1381 Styling updates + wiki page on contributions and sankey
  activity_browser/docs/wiki/Flow-Scenarios.md
  activity_browser/docs/wiki/Getting-Started.md
  activity_browser/docs/wiki/Home.md
  activity_browser/docs/wiki/Installation-Guide.md
  activity_browser/docs/wiki/LCA-Results.md
  activity_browser/docs/wiki/Parameters.md
  activity_browser/docs/wiki/Plugins.md
  activity_browser/docs/wiki/Uncertainty.md
  activity_browser/docs/wiki/assets/contribution_manipulation.png
  activity_browser/docs/wiki/assets/sankey_example.svg
  activity_browser/docs/wiki/assets/steel_production_example.svg
Labels: documentation
