Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2024-01, with the labels that each got.

#1190 Calculation Setup deletion dialogues
  activity_browser/controllers/project.py
  tests/test_calculation_setup.py
Labels: change

#1182 Fix empty database missing 'modified' time causing table to not show
  activity_browser/controllers/database.py
  activity_browser/ui/tables/models/base.py
  activity_browser/ui/tables/models/inventory.py
Labels: bug

#1180 resolve sankey caching bug
  activity_browser/ui/web/sankey_navigator.py
Labels: bug

#1194 Read project list in settings wizard from database
  activity_browser/ui/wizards/settings_wizard.py
Labels: change

#1197 Create unique version string for AB dev package
  .github/workflows/main.yaml
Labels: ci

#1200 Fixed threading issue in Biosphere patcher
  activity_browser/ui/widgets/dialog.py
  tests/test_add_default_data.py
Labels: bug

#1211 Resolve issue with heatmap color scaling with negative results
  activity_browser/ui/figures.py
Labels: bug

#1205 Wizard actually destroyed, any threads safely exited
  activity_browser/bwutils/importers.py
  activity_browser/ui/wizards/db_import_wizard.py
Labels: bug

#1203 Multiple improvements for the scenario import panel
  activity_browser/bwutils/superstructure/file_dialogs.py
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/bwutils/superstructure/utils.py
  activity_browser/layouts/tabs/LCA_setup.py
  activity_browser/ui/tables/LCA_setup.py
Labels: bug, change
