Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2024-06, with the labels that each got.

#1250 Reworked logging to catch all logs and prints and be prettier
  .github/conda-envs/test.yml
  activity_browser/__init__.py
  activity_browser/logger.py
  pytest.ini
  run-activity-browser.py
  tests/pytest.ini
  tests/wizards/test_uncertainty_wizard.py
Labels: bug, change

#1297 [CODE] Refactoring base.py sort model to be cleaner and easier to read.
  activity_browser/ui/tables/models/base.py
Labels: change

#1148 Allow project export and import
  .github/workflows/main.yaml
  activity_browser/actions/__init__.py
  activity_browser/actions/base.py
  activity_browser/actions/project/project_export.py
  activity_browser/actions/project/project_import.py
  activity_browser/bwutils/errors.py
  activity_browser/layouts/tabs/activity.py
  activity_browser/signals.py
  activity_browser/ui/menu_bar.py
  recipe/meta.yaml
  tests/actions/test_project_actions.py
Labels: feature

#1047 Database tree view for databases with ISIC data
  activity_browser/actions/activity/activity_duplicate_to_db.py
  activity_browser/bwutils/metadata.py
  activity_browser/layouts/tabs/project_manager.py
  activity_browser/static/database_classifications/ISIC_Rev_4_english_structure.txt
  activity_browser/ui/tables/LCA_setup.py
  activity_browser/ui/tables/__init__.py
  activity_browser/ui/tables/activity.py
  activity_browser/ui/tables/impact_categories.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/tables/models/__init__.py
  activity_browser/ui/tables/models/base.py
  activity_browser/ui/tables/models/inventory.py
  activity_browser/ui/tables/parameters.py
  activity_browser/ui/tables/views.py
Labels: feature

#1314 Add options for legacy biosphere versions to project setup wizard
  activity_browser/mod/bw2io/__init__.py
  activity_browser/mod/bw2io/importers/ecospold2_biosphere.py
  activity_browser/settings.py
  activity_browser/ui/wizards/db_import_wizard.py
  activity_browser/ui/wizards/project_setup_wizard.py
  tests/actions/test_various_actions.py
Labels: change

#1315 resolve tree-view not able to open activity correctly
  activity_browser/ui/tables/activity.py
  activity_browser/ui/tables/inventory.py
  activity_browser/ui/tables/models/inventory.py
Labels: bug

#1316 Treeview restores open/close state on update
  activity_browser/layouts/tabs/project_manager.py
  activity_browser/ui/tables/inventory.py
Labels: change
