Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2024-08, with the labels that each got.

#1324 Improved handling of different classification systems formats
  activity_browser/bwutils/metadata.py
Labels: change

#1333 Fix importing .z7 files directly
  activity_browser/ui/wizards/db_import_wizard.py
Labels: bug, prio:high

#1334 Fixed breaking bug in ABAction buttons
  activity_browser/actions/base.py
Labels: bug, prio:high

#1335 Disable collapsible panels in activity details
  activity_browser/layouts/tabs/activity.py
Labels: change

#1339 Added warning dialogue to ActivityDelete action
  activity_browser/actions/activity/activity_delete.py
Labels: feature

#1338 Added Open Impact Category to Calculation Setup screen
  activity_browser/actions/__init__.py
  activity_browser/actions/method/method_open.py
  activity_browser/ui/tables/LCA_setup.py
  activity_browser/ui/tables/models/lca_setup.py
Labels: feature

#1337 Added health checks to `ABSettings`
  activity_browser/settings.py
Labels: change

#1336 Logging changes
  activity_browser/__init__.py
  activity_browser/actions/calculation_setup/cs_delete.py
  activity_browser/actions/calculation_setup/cs_duplicate.py
  activity_browser/actions/calculation_setup/cs_new.py
  activity_browser/actions/calculation_setup/cs_rename.py
  activity_browser/actions/method/method_delete.py
  activity_browser/actions/method/method_duplicate.py
  activity_browser/actions/project/project_export.py
  activity_browser/actions/project/project_import.py
  activity_browser/actions/project/project_switch.py
  activity_browser/application.py
  activity_browser/bwutils/calculations.py
  activity_browser/bwutils/commontasks.py
  activity_browser/bwutils/ecoinvent_biosphere_versions/ecospold2biosphereimporter.py
  activity_browser/bwutils/metadata.py
  activity_browser/bwutils/montecarlo.py
  activity_browser/bwutils/multilca.py
  activity_browser/bwutils/sensitivity_analysis.py
  activity_browser/bwutils/strategies.py
  activity_browser/bwutils/superstructure/excel.py
  activity_browser/bwutils/superstructure/file_imports.py
  activity_browser/bwutils/superstructure/manager.py
  activity_browser/bwutils/superstructure/utils.py
  activity_browser/controllers/plugin.py
  activity_browser/info.py
  activity_browser/layouts/panels/panel.py
  activity_browser/layouts/panels/right.py
  activity_browser/layouts/tabs/LCA_results_tab.py
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/layouts/tabs/LCA_setup.py
  activity_browser/logger.py
  activity_browser/mod/bw2io/__init__.py
  activity_browser/mod/bw2io/ecoinvent.py
  activity_browser/settings.py
  activity_browser/ui/figures.py
  activity_browser/ui/statusbar.py
  activity_browser/ui/tables/LCA_setup.py
  activity_browser/ui/tables/models/activity.py
  activity_browser/ui/tables/models/base.py
  activity_browser/ui/tables/models/inventory.py
  activity_browser/ui/tables/models/lca_setup.py
  activity_browser/ui/tables/models/parameters.py
  activity_browser/ui/tables/views.py
  activity_browser/ui/web/base.py
  activity_browser/ui/web/navigator.py
  activity_browser/ui/web/sankey_navigator.py
  activity_browser/ui/widgets/biosphere_update.py
  activity_browser/ui/wizards/db_import_wizard.py
  activity_browser/ui/wizards/settings_wizard.py
  activity_browser/ui/wizards/uncertainty.py
  run-activity-browser.py
Labels: change

#1351 Fix python version support
  .github/workflows/install-canary.yaml
  setup.py
Labels: change
