Repository LCA-ActivityBrowser/activity-browser, pull requests merged in 2024-12, with the labels that each got.

#1046 CA updates + CA bugfixes + First-Tier contribution analysis tab
  activity_browser/bwutils/multilca.py
  activity_browser/docs/wiki/LCA-Results.md
  activity_browser/docs/wiki/assets/ca_positive_negative_example.png
  activity_browser/docs/wiki/assets/contribution_manipulation.png
  activity_browser/layouts/tabs/LCA_results_tabs.py
  activity_browser/ui/figures.py
  activity_browser/ui/tables/models/lca_results.py
Labels: bug, feature

#1416 Flow Scenario wiki + update scenario help-menu
  activity_browser/docs/wiki/Flow-Scenarios.md
  activity_browser/docs/wiki/assets/sdf_addition_combination.png
  activity_browser/docs/wiki/assets/sdf_product_combination.png
  activity_browser/layouts/tabs/LCA_setup.py
Labels: documentation

#1420 Parameter Scenario fixes
  activity_browser/bwutils/manager.py
  activity_browser/bwutils/superstructure/dataframe.py
  activity_browser/bwutils/utils.py
  activity_browser/ui/tables/models/scenarios.py
Labels: bug

#1421 resolve faulty disable of `range` and `score` buttons
  activity_browser/docs/wiki/LCA-Results.md
  activity_browser/layouts/tabs/LCA_results_tabs.py
Labels: change

#1423 Hide uncertainty on CF table load
  activity_browser/layouts/tabs/impact_categories.py
Labels: bug
